on:
  push:

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch name
        run: |
          echo 'ref_name: ${{ github.ref_name }}'
          echo 'ref: ${{ github.ref }}'
          echo 'head_ref: ${{ github.head_ref }}'
