
on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Prepare'
        run: |
          mkdir artifact

      - uses: mxschmitt/action-tmate@v3

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: |
            artifact/*
