name: 'Try cache restore/save'

on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Restore a cache'
        id: step-1
        uses: actions/cache/restore@v3
        with:
          path: tmp-cache
          key: tmp-cache

      - name: 'Test the cache'
        if: ${{ steps.step-1.outputs.cache-hit != true }}
        run: |
          echo 'cache-hit=${{ steps.step-1.outputs.cache-hit }}'

      - name: 'Test the cache'
        if: ${{ steps.step-1.outputs.cache-hit == true }}
        run: |
          echo 'cache-hit=${{ steps.step-1.outputs.cache-hit }}'

      - name: 'Make a data'
        run: |
          echo 'cache-hit=${{ steps.step-1.outputs.cache-hit }}'
          if [ '${{ steps.step-1.outputs.cache-hit }}' != true ]; then
            mkdir tmp-cache
          fi
          date -R > tmp-cache/date.txt

      - name: 'Save a cache'
        if: ${{ steps.step-1.outputs.cache-hit != true }}
        uses: actions/cache/save@v3
        with:
          path: tmp-cache
          key: tmp-cache
